name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5
        options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker-compose services
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for services (basic)
        run: |
          sleep 5
          docker ps -a

      - name: Run smoke checks
        run: |
          # Check love container output
          docker run --rm tri_demo_love || true
          docker run --rm tri_demo_hello || true

      - name: Tear down
        if: always()
        run: docker-compose down
